import {
  Palette,
  Sun,
  Zap,
  Camera,
  Monitor,
  Globe,
  ShoppingCart,
  ShieldCheck,
  Wrench,
  Hammer,
  Droplets,
  Flame,
  Plug,
  Lightbulb,
  Building2,
  Factory,
  Home,
  Lock,
  Wifi,
  Cloud,
  Code,
  Users,
  Truck,
  Phone,
  Power,
  Leaf,
  Paintbrush,
  PenTool,
  LayoutTemplate,
  FileText,
  Database,
  Server,
  Cpu,
  Video,
  Bell,
  Fuel,
  Ruler,
  Cog,
  Settings,
  MapPin,
  Award,
  Sparkles,
  Recycle,
  Wind,
  Thermometer,
  Timer,
  BatteryCharging,
  Car,
  KeyRound,
  TreePine,
  Briefcase,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

// A curated set of icon names the admin can pick from when configuring a
// service. Icons are imported explicitly above so we never pull the entire
// lucide bundle into the admin bundle or the public website.
export const SERVICE_ICON_OPTIONS = [
  'Palette',
  'Sun',
  'Zap',
  'Camera',
  'Monitor',
  'Globe',
  'ShoppingCart',
  'ShieldCheck',
  'Wrench',
  'Hammer',
  'Droplets',
  'Flame',
  'Plug',
  'Lightbulb',
  'Building2',
  'Factory',
  'Home',
  'Lock',
  'Wifi',
  'Cloud',
  'Code',
  'Users',
  'Truck',
  'Phone',
  'Power',
  'Leaf',
  'Paintbrush',
  'PenTool',
  'LayoutTemplate',
  'FileText',
  'Database',
  'Server',
  'Cpu',
  'Video',
  'Bell',
  'Fuel',
  'Ruler',
  'Cog',
  'Settings',
  'MapPin',
  'Award',
  'Sparkles',
  'Recycle',
  'Wind',
  'Thermometer',
  'Timer',
  'BatteryCharging',
  'Car',
  'KeyRound',
  'TreePine',
] as const;

const ICON_MAP: Record<string, LucideIcon> = {
  Palette,
  Sun,
  Zap,
  Camera,
  Monitor,
  Globe,
  ShoppingCart,
  ShieldCheck,
  Wrench,
  Hammer,
  Droplets,
  Flame,
  Plug,
  Lightbulb,
  Building2,
  Factory,
  Home,
  Lock,
  Wifi,
  Cloud,
  Code,
  Users,
  Truck,
  Phone,
  Power,
  Leaf,
  Paintbrush,
  PenTool,
  LayoutTemplate,
  FileText,
  Database,
  Server,
  Cpu,
  Video,
  Bell,
  Fuel,
  Ruler,
  Cog,
  Settings,
  MapPin,
  Award,
  Sparkles,
  Recycle,
  Wind,
  Thermometer,
  Timer,
  BatteryCharging,
  Car,
  KeyRound,
  TreePine,
};

const FALLBACK_ICON = Briefcase;

/** Resolve an admin-configured icon name to its component. */
export function resolveServiceIcon(name?: string | null): LucideIcon {
  if (!name) return FALLBACK_ICON;
  return ICON_MAP[name] ?? FALLBACK_ICON;
}

/** Render the configured icon for a service, falling back to a default. */
export function ServiceIcon({ name, ...props }: { name?: string | null } & LucideProps) {
  const Icon = resolveServiceIcon(name);
  return <Icon {...props} />;
}
