import type { NavItem, ServiceItem, IndustryItem, ProcessStep, StatItem, TestimonialItem, FAQItem, ProjectItem } from '../types';

export const NAVIGATION: NavItem[] = [
  { label: 'Home', href: '/' },
  {
    label: 'Services',
    href: '/services',
    children: [
      { label: 'Interior Design', href: '/services/interior-design' },
      { label: 'Solar Installation', href: '/services/solar-installation' },
      { label: 'Electrical Works', href: '/services/electrical-works' },
      { label: 'CCTV Installation', href: '/services/cctv-installation' },
      { label: 'Signage Solutions', href: '/services/signage-solutions' },
      { label: 'Website & IT Services', href: '/services/website-it-services' },
      { label: 'E-Commerce Development', href: '/services/ecommerce-development' },
      { label: 'Security Consulting', href: '/services/security-consulting' },
    ],
  },
  { label: 'Industries', href: '/industries' },
  { label: 'How It Works', href: '/how-it-works' },
  { label: 'Projects', href: '/projects' },
  { label: 'About', href: '/about' },
  { label: 'Resources', href: '/resources' },
  { label: 'Contact', href: '/contact' },
];

export const SERVICES: ServiceItem[] = [
  {
    id: '1',
    name: 'Interior Design',
    slug: 'interior-design',
    description: 'Transform your workspace with our comprehensive interior design solutions. From concept to completion, we create environments that inspire productivity and reflect your brand identity.',
    shortDescription: 'Complete interior design and fit-out solutions for commercial spaces.',
    icon: 'Palette',
    features: [
      'Space planning and layout optimization',
      'Custom furniture and millwork',
      'Material and finish selection',
      'Lighting design',
      'Project management',
      'Turnkey fit-out solutions',
    ],
    category: 'Infrastructure',
  },
  {
    id: '2',
    name: 'Solar Installation',
    slug: 'solar-installation',
    description: 'Deploy sustainable energy solutions with our end-to-end solar installation services. We handle everything from site assessment to commissioning and ongoing maintenance.',
    shortDescription: 'End-to-end solar energy solutions for commercial and industrial properties.',
    icon: 'Sun',
    features: [
      'Site assessment and feasibility study',
      'System design and engineering',
      'Panel installation and wiring',
      'Inverter setup and grid integration',
      'Monitoring and maintenance',
      'Government subsidy assistance',
    ],
    category: 'Energy',
  },
  {
    id: '3',
    name: 'Electrical Works',
    slug: 'electrical-works',
    description: 'Professional electrical infrastructure services for commercial and industrial facilities. Our certified electricians deliver safe, code-compliant installations.',
    shortDescription: 'Certified electrical installations, maintenance, and upgrades.',
    icon: 'Zap',
    features: [
      'Electrical panel installation',
      'Wiring and cable management',
      'Power distribution systems',
      'Backup power solutions',
      'Electrical safety audits',
      'Energy efficiency upgrades',
    ],
    category: 'Infrastructure',
  },
  {
    id: '4',
    name: 'CCTV Installation',
    slug: 'cctv-installation',
    description: 'Secure your premises with advanced surveillance systems. We design, install, and maintain CCTV networks tailored to your security requirements.',
    shortDescription: 'Advanced surveillance and security camera systems.',
    icon: 'Camera',
    features: [
      'IP and analog camera systems',
      'Network Video Recorder (NVR) setup',
      'Remote monitoring solutions',
      'Access control integration',
      'Night vision and analytics',
      'Annual maintenance contracts',
    ],
    category: 'Security',
  },
  {
    id: '5',
    name: 'Signage Solutions',
    slug: 'signage-solutions',
    description: 'Make a lasting impression with professional signage that communicates your brand. From indoor displays to large-format outdoor signage.',
    shortDescription: 'Professional signage design, fabrication, and installation.',
    icon: 'Monitor',
    features: [
      'LED and digital signage',
      'Channel letter signs',
      'Wayfinding and directional signs',
      'Outdoor billboards and hoardings',
      'Window graphics and wraps',
      'Signage maintenance',
    ],
    category: 'Branding',
  },
  {
    id: '6',
    name: 'Website & IT Services',
    slug: 'website-it-services',
    description: 'Build your digital presence with our full-stack IT services. From web development to infrastructure setup, we power your technology needs.',
    shortDescription: 'Web development, IT infrastructure, and digital solutions.',
    icon: 'Globe',
    features: [
      'Custom website development',
      'Web application development',
      'IT infrastructure setup',
      'Cloud hosting and deployment',
      'Domain and email configuration',
      'Technical support and maintenance',
    ],
    category: 'Technology',
  },
  {
    id: '7',
    name: 'E-Commerce Development',
    slug: 'ecommerce-development',
    description: 'Launch or upgrade your online store with our specialized e-commerce solutions. We build scalable, conversion-optimized platforms.',
    shortDescription: 'Custom e-commerce platforms and online store solutions.',
    icon: 'ShoppingCart',
    features: [
      'Custom e-commerce platforms',
      'Payment gateway integration',
      'Inventory management systems',
      'Marketplace integrations',
      'Performance optimization',
      'Analytics and reporting',
    ],
    category: 'Technology',
  },
  {
    id: '8',
    name: 'Security Consulting',
    slug: 'security-consulting',
    description: 'Protect your business with expert security consulting. We assess risks and design comprehensive security frameworks for your infrastructure.',
    shortDescription: 'Expert security assessments and comprehensive protection strategies.',
    icon: 'ShieldCheck',
    features: [
      'Security risk assessment',
      'Access control planning',
      'CCTV and surveillance design',
      'Fire safety consulting',
      'Compliance audits',
      'Emergency response planning',
    ],
    category: 'Security',
  },
];

export const INDUSTRIES: IndustryItem[] = [
  {
    id: '1',
    name: 'Retail',
    slug: 'retail',
    description: 'End-to-end infrastructure solutions for retail stores, showrooms, and chain outlets. From interior fit-outs to security systems.',
    icon: 'Store',
    services: ['Interior Design', 'CCTV Installation', 'Signage Solutions', 'Electrical Works'],
  },
  {
    id: '2',
    name: 'Healthcare',
    slug: 'healthcare',
    description: 'Specialized infrastructure for hospitals, clinics, and diagnostic centers with compliance-first approach.',
    icon: 'Heart',
    services: ['Interior Design', 'Electrical Works', 'CCTV Installation', 'Security Consulting'],
  },
  {
    id: '3',
    name: 'Education',
    slug: 'education',
    description: 'Smart campus infrastructure for schools, colleges, and training centers.',
    icon: 'GraduationCap',
    services: ['IT Services', 'CCTV Installation', 'Electrical Works', 'Solar Installation'],
  },
  {
    id: '4',
    name: 'Hospitality',
    slug: 'hospitality',
    description: 'Premium infrastructure for hotels, resorts, and restaurants that enhances guest experience.',
    icon: 'Hotel',
    services: ['Interior Design', 'Solar Installation', 'Signage Solutions', 'Security Consulting'],
  },
  {
    id: '5',
    name: 'Manufacturing',
    slug: 'manufacturing',
    description: 'Industrial-grade infrastructure solutions for factories, warehouses, and production facilities.',
    icon: 'Factory',
    services: ['Electrical Works', 'Solar Installation', 'Security Consulting', 'CCTV Installation'],
  },
  {
    id: '6',
    name: 'Corporate Offices',
    slug: 'corporate-offices',
    description: 'Modern office infrastructure that fosters productivity and reflects corporate culture.',
    icon: 'Building2',
    services: ['Interior Design', 'IT Services', 'Electrical Works', 'CCTV Installation'],
  },
  {
    id: '7',
    name: 'Warehouses',
    slug: 'warehouses',
    description: 'Secure and efficient warehouse infrastructure with smart monitoring solutions.',
    icon: 'Warehouse',
    services: ['CCTV Installation', 'Electrical Works', 'Solar Installation', 'Security Consulting'],
  },
  {
    id: '8',
    name: 'Restaurants',
    slug: 'restaurants',
    description: 'Complete fit-out and infrastructure solutions for restaurants, cafes, and cloud kitchens.',
    icon: 'UtensilsCrossed',
    services: ['Interior Design', 'Electrical Works', 'CCTV Installation', 'Signage Solutions'],
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  { step: 1, title: 'Requirement', description: 'Share your project needs through our guided wizard or consultation call.', icon: 'ClipboardList' },
  { step: 2, title: 'Consultation', description: 'Our experts discuss your requirements and recommend the best approach.', icon: 'MessageSquare' },
  { step: 3, title: 'Site Visit', description: 'Our team visits your location to assess the site and finalize plans.', icon: 'MapPin' },
  { step: 4, title: 'Quotation', description: 'Receive a detailed, transparent quotation with itemized costs.', icon: 'FileText' },
  { step: 5, title: 'Execution', description: 'Our vetted vendors execute the project with regular progress updates.', icon: 'Hammer' },
  { step: 6, title: 'Handover', description: 'Quality inspection, documentation, and seamless project handover.', icon: 'CheckCircle' },
];

export const STATS: StatItem[] = [
  { label: 'Projects Completed', value: '500', suffix: '+', description: 'Successfully delivered across industries' },
  { label: 'Response Time', value: '24', suffix: ' hrs', description: 'Average initial response time' },
  { label: 'Client Satisfaction', value: '98', suffix: '%', description: 'Based on post-project surveys' },
  { label: 'Vendor Network', value: '200', suffix: '+', description: 'Verified and trusted partners' },
  { label: 'Years Experience', value: '10', suffix: '+', description: 'In managed infrastructure services' },
];

export const FEATURED_PROJECTS: ProjectItem[] = [
  {
    id: '1',
    title: 'Tech Park Office Complex',
    category: 'Interior Design',
    industry: 'Corporate Offices',
    description: 'Complete interior fit-out for a 50,000 sq ft tech park including workspaces, meeting rooms, and recreational areas.',
    services: ['Interior Design', 'Electrical Works', 'IT Services'],
  },
  {
    id: '2',
    title: 'Solar Farm Installation',
    category: 'Solar Installation',
    industry: 'Manufacturing',
    description: '2MW solar installation for an industrial manufacturing facility reducing energy costs by 40%.',
    services: ['Solar Installation', 'Electrical Works'],
  },
  {
    id: '3',
    title: 'Smart Retail Chain',
    category: 'CCTV Installation',
    industry: 'Retail',
    description: 'Centralized surveillance system across 25 retail outlets with remote monitoring capabilities.',
    services: ['CCTV Installation', 'Security Consulting'],
  },
  {
    id: '4',
    title: 'Hotel Renovation Project',
    category: 'Interior Design',
    industry: 'Hospitality',
    description: 'Full renovation of a 120-room hotel including lobby, restaurant, and conference facilities.',
    services: ['Interior Design', 'Signage Solutions', 'Electrical Works'],
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    role: 'Facilities Director',
    company: 'TechVista Solutions',
    content: 'Nexus transformed our office space beautifully. Their managed approach meant we had one point of contact for interior design, electrical work, and IT setup. The project was delivered on time and within budget.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Priya Sharma',
    role: 'Operations Head',
    company: 'GreenEnergy Corp',
    content: 'The solar installation project was handled end-to-end with exceptional professionalism. From site assessment to commissioning, Nexus coordinated everything seamlessly. Our energy bills dropped by 35%.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Amit Patel',
    role: 'Owner',
    company: 'Patel Retail Group',
    content: 'Managing infrastructure across 30+ retail locations was a nightmare until we found Nexus. Their vendor network and project management capabilities are outstanding.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Sneha Reddy',
    role: 'CEO',
    company: 'MedCare Hospitals',
    content: 'For our new hospital wing, we needed a partner who understood healthcare compliance. Nexus delivered a complete infrastructure solution that met all regulatory requirements.',
    rating: 5,
  },
  {
    id: '5',
    name: 'Vikram Singh',
    role: 'Managing Director',
    company: 'Singh Manufacturing',
    content: 'Nexus handled our factory electrification and solar installation simultaneously. Their coordination between different vendor teams was impressive. Highly recommended for industrial projects.',
    rating: 5,
  },
];

export const FAQS: FAQItem[] = [
  {
    id: '1',
    question: 'What is Nexus Managed Services?',
    answer: 'Nexus is a managed infrastructure platform that coordinates trusted vendors for interior design, solar installation, electrical works, CCTV, signage, and IT projects. We serve as your single point of contact, managing the entire project lifecycle from requirement gathering to handover.',
    category: 'General',
  },
  {
    id: '2',
    question: 'How does the quote request process work?',
    answer: 'Simply click "Get Free Quote" and follow our guided wizard. Select the services you need, provide project details, upload any reference images, and create an account. Our team will review your requirements and respond within 24 hours with a detailed consultation plan.',
    category: 'General',
  },
  {
    id: '3',
    question: 'What areas do you serve?',
    answer: 'We are currently headquartered in Lucknow and serve projects across Uttar Pradesh and surrounding regions. For large-scale projects, we can coordinate across multiple locations in India through our extensive vendor network.',
    category: 'General',
  },
  {
    id: '4',
    question: 'How many services can I include in a single quote?',
    answer: 'You can select multiple services in a single quote request. This is one of our key advantages — we coordinate all services under one project, ensuring seamless execution and consistent quality across all workstreams.',
    category: 'Quotation',
  },
  {
    id: '5',
    question: 'Is there any cost for the initial consultation?',
    answer: 'No, the initial consultation is completely free. Our team will discuss your requirements, suggest the best approach, and provide a detailed quotation with transparent pricing before any commitment is needed.',
    category: 'Quotation',
  },
  {
    id: '6',
    question: 'How do you ensure quality of work?',
    answer: 'All vendors in our network are thoroughly vetted and verified. We implement a rigorous quality inspection process at every milestone, provide regular progress updates, and maintain accountability through our project management system until successful handover.',
    category: 'Quality',
  },
  {
    id: '7',
    question: 'Can I track my project progress online?',
    answer: 'Yes! Once your project is confirmed, you get access to our Client Portal where you can track real-time progress, view timelines, communicate with the project team, access documents, and receive status updates.',
    category: 'Projects',
  },
  {
    id: '8',
    question: 'What payment terms do you offer?',
    answer: 'We offer flexible payment terms typically structured as: advance payment to begin, milestone-based payments during execution, and final payment upon successful handover. Specific terms are detailed in the quotation and can be discussed during consultation.',
    category: 'Payment',
  },
  {
    id: '9',
    question: 'Do you provide warranties on completed work?',
    answer: 'Yes, all projects come with warranty coverage as specified in the quotation. This typically includes workmanship warranty from vendors and material warranties from manufacturers. Extended maintenance contracts are also available.',
    category: 'Quality',
  },
  {
    id: '10',
    question: 'What industries do you specialize in?',
    answer: 'We serve a wide range of industries including Retail, Healthcare, Education, Hospitality, Manufacturing, Corporate Offices, Warehouses, and Restaurants. Our approach is tailored to meet the specific infrastructure requirements of each industry.',
    category: 'General',
  },
  {
    id: '11',
    question: 'How long does a typical project take?',
    answer: 'Project timelines vary based on scope and complexity. A single-service project might take 1-2 weeks, while a multi-service fit-out could take 4-12 weeks. We provide detailed timelines during the quotation phase with clear milestones.',
    category: 'Projects',
  },
  {
    id: '12',
    question: 'Can I modify my requirements after submitting a quote?',
    answer: 'Absolutely. The initial quote request is just the starting point. During the consultation phase, you can refine, add, or modify requirements. We adapt the scope and pricing accordingly before any commitment is made.',
    category: 'Quotation',
  },
];

export const BUDGET_RANGES = [
  'Under ₹1 Lakh',
  '₹1 - 5 Lakhs',
  '₹5 - 10 Lakhs',
  '₹10 - 25 Lakhs',
  '₹25 - 50 Lakhs',
  '₹50 Lakhs - 1 Crore',
  'Above ₹1 Crore',
];

export const TIMELINE_OPTIONS = [
  'Urgent (Within 1 week)',
  '1 - 2 Weeks',
  '2 - 4 Weeks',
  '1 - 2 Months',
  '2 - 3 Months',
  '3 - 6 Months',
  'Flexible / No Rush',
];

export const PROPERTY_TYPES = [
  'Office Space',
  'Retail Store',
  'Warehouse',
  'Factory / Industrial',
  'Restaurant / Cafe',
  'Hotel / Hospitality',
  'Healthcare Facility',
  'Educational Institution',
  'Residential',
  'Other',
];

export const COMPANY_INFO = {
  name: 'Nexus Managed Services',
  tagline: 'One Partner For All Your Business Infrastructure Needs',
  location: 'Lucknow, India',
  email: 'info@nexusmcs.com',
  phone: '+91 XXXXX XXXXX',
  address: 'Lucknow, Uttar Pradesh, India',
};
